.TH "C:/Users/mathh/GitHub/Molecular-Spintronics-Research-Project/MSD Research Project - Latest Development Version/src/mmt.h" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mathh/GitHub/Molecular-Spintronics-Research-Project/MSD Research Project - Latest Development Version/src/mmt.h \- Contains functions for reading and parsing MMT (\fBMSD\fP Molecule Text) files, such as those created by the \fBMSD\fP Molecule Builder webtool\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'MSD\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBudc\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > T \fBudc::parseline\fP (istream &in)"
.br
.ti -1c
.RI "template<> string \fBudc::parseline\fP (istream &in)"
.br
.ti -1c
.RI "template<> istringstream \fBudc::parseline\fP (istream &in)"
.br
.ti -1c
.RI "template<> void \fBudc::parseline\fP (istream &in)"
.br
.ti -1c
.RI "template<typename T > T \fBudc::parseline\fP (const string &str)"
.br
.ti -1c
.RI "istream & \fBudc::operator>>\fP (istream &in, \fBudc::Vector\fP &v)"
.br
.ti -1c
.RI "\fBMSD::MolProto\fP \fBudc::readMMT\fP (istream &src)"
.br
.RI "Parses MMT file data from the given text istream, and saves it as a \fBMSD::MolProto\fP object\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains functions for reading and parsing MMT (\fBMSD\fP Molecule Text) files, such as those created by the \fBMSD\fP Molecule Builder webtool\&. 


.PP
\fBAuthor\fP
.RS 4
Christopher D'Angelo (chris@mathhead200.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
September 2, 2022
.RE
.PP
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
