.TH "MSD.MSD.Parameters" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSD.MSD.Parameters
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMSD\&._StructWithDict\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, *args, **kw)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBkT\fP"
.br
.ti -1c
.RI "\fBB\fP"
.br
.ti -1c
.RI "\fBSR\fP"
.br
.ti -1c
.RI "\fBFR\fP"
.br
.ti -1c
.RI "\fBJLR\fP"
.br
.ti -1c
.RI "\fBJe0R\fP"
.br
.ti -1c
.RI "\fBJe1LR\fP"
.br
.ti -1c
.RI "\fBJeeLR\fP"
.br
.ti -1c
.RI "\fBbLR\fP"
.br
.ti -1c
.RI "\fBAR\fP"
.br
.ti -1c
.RI "\fBDLR\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def MSD\&.MSD\&.Parameters\&.__init__ ( self, * args, ** kw)"

.PP
Reimplemented from \fBMSD\&._StructWithDict\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "MSD\&.MSD\&.Parameters\&.AR"

.SS "MSD\&.MSD\&.Parameters\&.B"

.SS "MSD\&.MSD\&.Parameters\&.bLR"

.SS "MSD\&.MSD\&.Parameters\&.DLR"

.SS "MSD\&.MSD\&.Parameters\&.FR"

.SS "MSD\&.MSD\&.Parameters\&.Je0R"

.SS "MSD\&.MSD\&.Parameters\&.Je1LR"

.SS "MSD\&.MSD\&.Parameters\&.JeeLR"

.SS "MSD\&.MSD\&.Parameters\&.JLR"

.SS "MSD\&.MSD\&.Parameters\&.kT"

.SS "MSD\&.MSD\&.Parameters\&.SR"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
