.TH "MSD._StructWithDict" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSD._StructWithDict \- Version of ctypes\&.Structure that defines \fBdict\fP and overrides \fBrepr\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Structure\&.
.PP
Inherited by \fBMSD\&.MSD\&.Parameters\fP, \fBMSD\&.MSD\&.Results\fP, \fBMSD\&.Vector\fP, and \fBMSD\&._MMTStruct\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, *args, **kw)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Version of ctypes\&.Structure that defines \fBdict\fP and overrides \fBrepr\fP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def MSD\&._StructWithDict\&.__init__ ( self, * args, ** kw)"

.PP
Reimplemented in \fBMSD\&._MMTStruct\fP, \fBMSD\&.Vector\fP, \fBMSD\&.Molecule\&.EdgeParameters\fP, \fBMSD\&.Molecule\&.NodeParameters\fP, \fBMSD\&.MSD\&.Parameters\fP, and \fBMSD\&.MSD\&.Results\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
