.TH "udc::Molecule::NodeIterator" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udc::Molecule::NodeIterator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSD\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBgetIndex\fP () const"
.br
.ti -1c
.RI "\fBNodeParameters\fP \fBgetParameters\fP () const"
.br
.ti -1c
.RI "\fBEdgeIterable\fP \fBgetNeighbors\fP () const"
.br
.ti -1c
.RI "unsigned int \fBoperator*\fP () const"
.br
.ti -1c
.RI "unsigned int \fBoperator[]\fP (int) const"
.br
.ti -1c
.RI "\fBoperator unsigned int\fP () const"
.br
.ti -1c
.RI "\fBNodeIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBNodeIterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBNodeIterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBNodeIterator\fP \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "\fBNodeIterator\fP & \fBoperator+=\fP (int)"
.br
.ti -1c
.RI "\fBNodeIterator\fP & \fBoperator\-=\fP (int)"
.br
.ti -1c
.RI "\fBNodeIterator\fP \fBoperator+\fP (int) const"
.br
.ti -1c
.RI "\fBNodeIterator\fP \fBoperator\-\fP (int) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBNodeIterator\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBNodeIterator\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBNodeIterator\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBNodeIterator\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBNodeIterator\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBNodeIterator\fP &) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBNodeIterable\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "unsigned int udc::Molecule::NodeIterator::getIndex () const"

.SS "\fBMolecule::EdgeIterable\fP udc::Molecule::NodeIterator::getNeighbors () const"

.SS "\fBMolecule::NodeParameters\fP udc::Molecule::NodeIterator::getParameters () const"

.SS "udc::Molecule::NodeIterator::operator unsigned int () const"

.SS "bool udc::Molecule::NodeIterator::operator!= (const \fBNodeIterator\fP & iter) const"

.SS "unsigned int udc::Molecule::NodeIterator::operator* () const"

.SS "\fBMolecule::NodeIterator\fP udc::Molecule::NodeIterator::operator+ (int offset) const"

.SS "\fBMolecule::NodeIterator\fP & udc::Molecule::NodeIterator::operator++ ()"

.SS "\fBMolecule::NodeIterator\fP udc::Molecule::NodeIterator::operator++ (int)"

.SS "\fBMolecule::NodeIterator\fP & udc::Molecule::NodeIterator::operator+= (int offset)"

.SS "\fBMolecule::NodeIterator\fP udc::Molecule::NodeIterator::operator\- (int offset) const"

.SS "\fBMolecule::NodeIterator\fP & udc::Molecule::NodeIterator::operator\-\- ()"

.SS "\fBMolecule::NodeIterator\fP udc::Molecule::NodeIterator::operator\-\- (int)"

.SS "\fBMolecule::NodeIterator\fP & udc::Molecule::NodeIterator::operator\-= (int offset)"

.SS "bool udc::Molecule::NodeIterator::operator< (const \fBNodeIterator\fP & iter) const"

.SS "bool udc::Molecule::NodeIterator::operator<= (const \fBNodeIterator\fP & iter) const"

.SS "bool udc::Molecule::NodeIterator::operator== (const \fBNodeIterator\fP & iter) const"

.SS "bool udc::Molecule::NodeIterator::operator> (const \fBNodeIterator\fP & iter) const"

.SS "bool udc::Molecule::NodeIterator::operator>= (const \fBNodeIterator\fP & iter) const"

.SS "unsigned int udc::Molecule::NodeIterator::operator[] (int offset) const"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBNodeIterable\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
