.TH "MSD" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSD
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_MMTStruct\fP"
.br
.RI "Adds the MSD-Molecule-Text, \fBmmt()\fP method for subclasses\&. "
.ti -1c
.RI "class \fB_StructWithDict\fP"
.br
.RI "Version of ctypes\&.Structure that defines \fBdict\fP and overrides \fBrepr\fP "
.ti -1c
.RI "class \fBMolecule\fP"
.br
.ti -1c
.RI "class \fBMSD\fP"
.br
.ti -1c
.RI "class \fBVector\fP"
.br
.RI "Python version of \fBudc::Vector\fP class in \fBVector\&.h\fP\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMSD_EXPORT_DLL_PATH\fP = os\&.path\&.join(os\&.path\&.realpath(os\&.path\&.dirname(__file__)), 'MSD\-export\&.dll')"
.br
.ti -1c
.RI "\fBmsd_clib\fP = CDLL(\fBMSD_EXPORT_DLL_PATH\fP)"
.br
.ti -1c
.RI "\fBPI\fP = c_double\&.in_dll(\fBmsd_clib\fP, 'PI')\&.value"
.br
.ti -1c
.RI "\fBE\fP = c_double\&.in_dll(\fBmsd_clib\fP, 'E')\&.value"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "MSD\&.E = c_double\&.in_dll(\fBmsd_clib\fP, 'E')\&.value"

.SS "MSD\&.msd_clib = CDLL(\fBMSD_EXPORT_DLL_PATH\fP)"

.SS "MSD\&.MSD_EXPORT_DLL_PATH = os\&.path\&.join(os\&.path\&.realpath(os\&.path\&.dirname(__file__)), 'MSD\-export\&.dll')"

.SS "MSD\&.PI = c_double\&.in_dll(\fBmsd_clib\fP, 'PI')\&.value"

.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
