.TH "udc::MSD::Parameters" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udc::MSD::Parameters
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSD\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParameters\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBParameters\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBParameters\fP &) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBkT\fP"
.br
.ti -1c
.RI "\fBVector\fP \fBB\fP"
.br
.ti -1c
.RI "double \fBSL\fP"
.br
.ti -1c
.RI "double \fBSR\fP"
.br
.ti -1c
.RI "double \fBFL\fP"
.br
.ti -1c
.RI "double \fBFR\fP"
.br
.ti -1c
.RI "double \fBJL\fP"
.br
.ti -1c
.RI "double \fBJR\fP"
.br
.ti -1c
.RI "double \fBJmL\fP"
.br
.ti -1c
.RI "double \fBJmR\fP"
.br
.ti -1c
.RI "double \fBJLR\fP"
.br
.ti -1c
.RI "double \fBJe0L\fP"
.br
.ti -1c
.RI "double \fBJe0R\fP"
.br
.ti -1c
.RI "double \fBJe1L\fP"
.br
.ti -1c
.RI "double \fBJe1R\fP"
.br
.ti -1c
.RI "double \fBJe1mL\fP"
.br
.ti -1c
.RI "double \fBJe1mR\fP"
.br
.ti -1c
.RI "double \fBJe1LR\fP"
.br
.ti -1c
.RI "double \fBJeeL\fP"
.br
.ti -1c
.RI "double \fBJeeR\fP"
.br
.ti -1c
.RI "double \fBJeemL\fP"
.br
.ti -1c
.RI "double \fBJeemR\fP"
.br
.ti -1c
.RI "double \fBJeeLR\fP"
.br
.ti -1c
.RI "double \fBbL\fP"
.br
.ti -1c
.RI "double \fBbR\fP"
.br
.ti -1c
.RI "double \fBbmL\fP"
.br
.ti -1c
.RI "double \fBbmR\fP"
.br
.ti -1c
.RI "double \fBbLR\fP"
.br
.ti -1c
.RI "\fBVector\fP \fBAL\fP"
.br
.ti -1c
.RI "\fBVector\fP \fBAR\fP"
.br
.ti -1c
.RI "\fBVector\fP \fBDL\fP"
.br
.ti -1c
.RI "\fBVector\fP \fBDR\fP"
.br
.ti -1c
.RI "\fBVector\fP \fBDmL\fP"
.br
.ti -1c
.RI "\fBVector\fP \fBDmR\fP"
.br
.ti -1c
.RI "\fBVector\fP \fBDLR\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "udc::MSD::Parameters::Parameters ()"

.SH "Member Function Documentation"
.PP 
.SS "bool udc::MSD::Parameters::operator!= (const \fBParameters\fP & p) const"

.SS "bool udc::MSD::Parameters::operator== (const \fBParameters\fP & p) const"

.SH "Member Data Documentation"
.PP 
.SS "\fBVector\fP udc::MSD::Parameters::AL"

.SS "\fBVector\fP udc::MSD::Parameters::AR"

.SS "\fBVector\fP udc::MSD::Parameters::B"

.SS "double udc::MSD::Parameters::bL"

.SS "double udc::MSD::Parameters::bLR"

.SS "double udc::MSD::Parameters::bmL"

.SS "double udc::MSD::Parameters::bmR"

.SS "double udc::MSD::Parameters::bR"

.SS "\fBVector\fP udc::MSD::Parameters::DL"

.SS "\fBVector\fP udc::MSD::Parameters::DLR"

.SS "\fBVector\fP udc::MSD::Parameters::DmL"

.SS "\fBVector\fP udc::MSD::Parameters::DmR"

.SS "\fBVector\fP udc::MSD::Parameters::DR"

.SS "double udc::MSD::Parameters::FL"

.SS "double udc::MSD::Parameters::FR"

.SS "double udc::MSD::Parameters::Je0L"

.SS "double udc::MSD::Parameters::Je0R"

.SS "double udc::MSD::Parameters::Je1L"

.SS "double udc::MSD::Parameters::Je1LR"

.SS "double udc::MSD::Parameters::Je1mL"

.SS "double udc::MSD::Parameters::Je1mR"

.SS "double udc::MSD::Parameters::Je1R"

.SS "double udc::MSD::Parameters::JeeL"

.SS "double udc::MSD::Parameters::JeeLR"

.SS "double udc::MSD::Parameters::JeemL"

.SS "double udc::MSD::Parameters::JeemR"

.SS "double udc::MSD::Parameters::JeeR"

.SS "double udc::MSD::Parameters::JL"

.SS "double udc::MSD::Parameters::JLR"

.SS "double udc::MSD::Parameters::JmL"

.SS "double udc::MSD::Parameters::JmR"

.SS "double udc::MSD::Parameters::JR"

.SS "double udc::MSD::Parameters::kT"

.SS "double udc::MSD::Parameters::SL"

.SS "double udc::MSD::Parameters::SR"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
