.TH "udc::SparseArrayValue< T >" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udc::SparseArrayValue< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SparseArray\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSparseArrayValue\fP ()"
.br
.ti -1c
.RI "T & \fBcreate\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBset\fP"
.br
.ti -1c
.RI "T \fBvalue\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBudc::SparseArrayValue\fP< T >::SparseArrayValue ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T > void \fBudc::SparseArrayValue\fP< T >::clear"

.SS "template<typename T > T & \fBudc::SparseArrayValue\fP< T >::create"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > bool \fBudc::SparseArrayValue\fP< T >::set"

.SS "template<typename T > T \fBudc::SparseArrayValue\fP< T >::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
