.TH "C:/Users/mathh/GitHub/Molecular-Spintronics-Research-Project/MSD Research Project - Latest Development Version/src Directory Reference" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mathh/GitHub/Molecular-Spintronics-Research-Project/MSD Research Project - Latest Development Version/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmmt\&.h\fP"
.br
.RI "Contains functions for reading and parsing MMT (\fBMSD\fP Molecule Text) files, such as those created by the \fBMSD\fP Molecule Builder webtool\&. "
.ti -1c
.RI "file \fBMSD\-export\&.cpp\fP"
.br
.RI "The extern 'C' version of \fBMSD\fP\&. May not contain the full functionality of \fBMSD\&.h\fP\&. To be used for Python3 (ctypes) binding, as well as any future bindings that require a C (cdecl) DLL\&. "
.ti -1c
.RI "file \fBMSD\&.h\fP"
.br
.RI "The core logic which all the apps use to run \fBMSD\fP simulations\&. Includes definitions and calculations\&. "
.ti -1c
.RI "file \fBSparseArray\&.h\fP"
.br
.ti -1c
.RI "file \fBudc\&.h\fP"
.br
.ti -1c
.RI "file \fBVector\&.h\fP"
.br
.in -1c
