.TH "C:/Users/mathh/GitHub/Molecular-Spintronics-Research-Project/MSD Research Project - Latest Development Version/src/MSD.h" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/mathh/GitHub/Molecular-Spintronics-Research-Project/MSD Research Project - Latest Development Version/src/MSD.h \- The core logic which all the apps use to run \fBMSD\fP simulations\&. Includes definitions and calculations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <random>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'Vector\&.h'\fP
.br
\fC#include 'udc\&.h'\fP
.br
\fC#include 'SparseArray\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBudc::Molecule\fP"
.br
.RI "An abstract molecule\&. "
.ti -1c
.RI "struct \fBudc::Molecule::EdgeParameters\fP"
.br
.RI "Information about an edge between two Nodes\&. "
.ti -1c
.RI "struct \fBudc::Molecule::NodeParameters\fP"
.br
.RI "local parameters "
.ti -1c
.RI "class \fBudc::Molecule::DeserializationException\fP"
.br
.ti -1c
.RI "class \fBudc::Molecule::NodeIterator\fP"
.br
.ti -1c
.RI "class \fBudc::Molecule::NodeIterable\fP"
.br
.ti -1c
.RI "class \fBudc::Molecule::EdgeIterator\fP"
.br
.ti -1c
.RI "class \fBudc::Molecule::EdgeIterable\fP"
.br
.ti -1c
.RI "class \fBudc::MSD\fP"
.br
.RI "An abstract Molecular Spintronic Device\&. "
.ti -1c
.RI "struct \fBudc::MSD::Parameters\fP"
.br
.ti -1c
.RI "struct \fBudc::MSD::Results\fP"
.br
.ti -1c
.RI "class \fBudc::MSD::Iterator\fP"
.br
.ti -1c
.RI "class \fBudc::MSD::MoleculeException\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBudc\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUDC_MSD_VERSION\fP   '6\&.2'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBudc::operator<<\fP (ostream &out, const MSD::Parameters &p)"
.br
.ti -1c
.RI "ostream & \fBudc::operator<<\fP (ostream &out, const MSD::Results &r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The core logic which all the apps use to run \fBMSD\fP simulations\&. Includes definitions and calculations\&. 


.PP
\fBAuthor\fP
.RS 4
Christopher D'Angelo 
.RE
.PP
\fBVersion\fP
.RS 4
6\&.2 
.RE
.PP
\fBDate\fP
.RS 4
2022-11-29
.RE
.PP
\fBCopyright\fP
.RS 4
Copyright (c) 2022 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define UDC_MSD_VERSION   '6\&.2'"

.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
