.TH "MSD.Molecule._Node" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSD.Molecule._Node \- Represents a specific molecule node\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBnext\fP (self)"
.br
.ti -1c
.RI "def \fBprev\fP (self)"
.br
.ti -1c
.RI "def \fB__init__\fP (self, iterable, start=(None, 0), direction=\fBFORWARD\fP)"
.br
.ti -1c
.RI "def \fB__del__\fP (self)"
.br
.ti -1c
.RI "def \fBclone\fP (self)"
.br
.ti -1c
.RI "def \fBgetParameters\fP (self)"
.br
.ti -1c
.RI "def \fB__eq__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__ne__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__lt__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__gt__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__le__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__ge__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__next__\fP (self)"
.br
.ti -1c
.RI "def \fB__iadd__\fP (self, offset)"
.br
.ti -1c
.RI "def \fB__isub__\fP (self, offset)"
.br
.ti -1c
.RI "def \fB__add__\fP (self, offset)"
.br
.ti -1c
.RI "def \fB__sub__\fP (self, offset)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBFORWARD\fP = (\fBnext\fP,)"
.br
.ti -1c
.RI "tuple \fBBACKWARD\fP = (\fBprev\fP,)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBmetaIndex\fP = property(fget = lambda self: self\&._i)"
.br
.ti -1c
.RI "\fBindex\fP = property(fget = lambda self: msd_clib\&.nodeIndex_i(self\&._node))"
.br
.ti -1c
.RI "\fBneighbors\fP = property(fget = lambda self: \fBMolecule\&._EdgeIterable\fP(msd_clib\&.getNeighbors(self\&._node)))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a specific molecule node\&. 

Also acts as a node iterator\&. Should not be construct directly! Should be constructed using \fBMolecule\&._NodeIterable\fP methods/properties\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def MSD\&.Molecule\&._Node\&.__init__ ( self,  iterable,  start = \fC(None, 0)\fP,  direction = \fC\fBFORWARD\fP\fP)"

.SS "def MSD\&.Molecule\&._Node\&.__del__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "def MSD\&.Molecule\&._Node\&.__add__ ( self,  offset)"

.SS "def MSD\&.Molecule\&._Node\&.__eq__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Node\&.__ge__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Node\&.__gt__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Node\&.__iadd__ ( self,  offset)"

.SS "def MSD\&.Molecule\&._Node\&.__isub__ ( self,  offset)"

.SS "def MSD\&.Molecule\&._Node\&.__le__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Node\&.__lt__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Node\&.__ne__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Node\&.__next__ ( self)"

.SS "def MSD\&.Molecule\&._Node\&.__sub__ ( self,  offset)"

.SS "def MSD\&.Molecule\&._Node\&.clone ( self)"

.SS "def MSD\&.Molecule\&._Node\&.getParameters ( self)"

.SS "def MSD\&.Molecule\&._Node\&.next ( self)"

.SS "def MSD\&.Molecule\&._Node\&.prev ( self)"

.SH "Member Data Documentation"
.PP 
.SS "tuple MSD\&.Molecule\&._Node\&.BACKWARD = (\fBprev\fP,)\fC [static]\fP"

.SS "tuple MSD\&.Molecule\&._Node\&.FORWARD = (\fBnext\fP,)\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "MSD\&.Molecule\&._Node\&.index = property(fget = lambda self: msd_clib\&.nodeIndex_i(self\&._node))\fC [static]\fP"

.SS "MSD\&.Molecule\&._Node\&.metaIndex = property(fget = lambda self: self\&._i)\fC [static]\fP"

.SS "MSD\&.Molecule\&._Node\&.neighbors = property(fget = lambda self: \fBMolecule\&._EdgeIterable\fP(msd_clib\&.getNeighbors(self\&._node)))\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
