.TH "MSD.Molecule._Edge" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSD.Molecule._Edge \- Represents a specific molecule edge\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBnext\fP (self)"
.br
.ti -1c
.RI "def \fBprev\fP (self)"
.br
.ti -1c
.RI "def \fB__init__\fP (self, iterable, start=(None, 0), \fBdirection\fP=\fBFORWARD\fP)"
.br
.ti -1c
.RI "def \fB__del__\fP (self)"
.br
.ti -1c
.RI "def \fBclone\fP (self)"
.br
.ti -1c
.RI "def \fBgetParameters\fP (self)"
.br
.ti -1c
.RI "def \fB__eq__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__ne__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__lt__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__gt__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__le__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__ge__\fP (self, other)"
.br
.ti -1c
.RI "def \fB__next__\fP (self)"
.br
.ti -1c
.RI "def \fB__iadd__\fP (self, offset)"
.br
.ti -1c
.RI "def \fB__isub__\fP (self, offset)"
.br
.ti -1c
.RI "def \fB__add__\fP (self, offset)"
.br
.ti -1c
.RI "def \fB__sub__\fP (self, offset)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "tuple \fBFORWARD\fP = (\fBnext\fP,)"
.br
.ti -1c
.RI "tuple \fBBACKWARD\fP = (\fBprev\fP,)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBmetaIndex\fP = property(fget = lambda self: self\&._i)"
.br
.ti -1c
.RI "\fBindex\fP = property(fget = lambda self: msd_clib\&.edgeIndex_i(self\&._edge))"
.br
.ti -1c
.RI "\fBsrc\fP = property(fget = lambda self: msd_clib\&.src_e(self\&._edge))"
.br
.ti -1c
.RI "\fBdest\fP = property(fget = lambda self: msd_clib\&.dest_e(self\&._edge))"
.br
.ti -1c
.RI "\fBdirection\fP = property(fget = lambda self: msd_clib\&.getDirection(self\&._edge))"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a specific molecule edge\&. 

Also acts as an edge iterator\&. Should not be construct directly! Should be constructed using \fBMolecule\&._EdgeIterable\fP methods/properties\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def MSD\&.Molecule\&._Edge\&.__init__ ( self,  iterable,  start = \fC(None, 0)\fP,  direction = \fC\fBFORWARD\fP\fP)"

.SS "def MSD\&.Molecule\&._Edge\&.__del__ ( self)"

.SH "Member Function Documentation"
.PP 
.SS "def MSD\&.Molecule\&._Edge\&.__add__ ( self,  offset)"

.SS "def MSD\&.Molecule\&._Edge\&.__eq__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Edge\&.__ge__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Edge\&.__gt__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Edge\&.__iadd__ ( self,  offset)"

.SS "def MSD\&.Molecule\&._Edge\&.__isub__ ( self,  offset)"

.SS "def MSD\&.Molecule\&._Edge\&.__le__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Edge\&.__lt__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Edge\&.__ne__ ( self,  other)"

.SS "def MSD\&.Molecule\&._Edge\&.__next__ ( self)"

.SS "def MSD\&.Molecule\&._Edge\&.__sub__ ( self,  offset)"

.SS "def MSD\&.Molecule\&._Edge\&.clone ( self)"

.SS "def MSD\&.Molecule\&._Edge\&.getParameters ( self)"

.SS "def MSD\&.Molecule\&._Edge\&.next ( self)"

.SS "def MSD\&.Molecule\&._Edge\&.prev ( self)"

.SH "Member Data Documentation"
.PP 
.SS "tuple MSD\&.Molecule\&._Edge\&.BACKWARD = (\fBprev\fP,)\fC [static]\fP"

.SS "tuple MSD\&.Molecule\&._Edge\&.FORWARD = (\fBnext\fP,)\fC [static]\fP"

.SH "Property Documentation"
.PP 
.SS "MSD\&.Molecule\&._Edge\&.dest = property(fget = lambda self: msd_clib\&.dest_e(self\&._edge))\fC [static]\fP"

.SS "MSD\&.Molecule\&._Edge\&.direction = property(fget = lambda self: msd_clib\&.getDirection(self\&._edge))\fC [static]\fP"

.SS "MSD\&.Molecule\&._Edge\&.index = property(fget = lambda self: msd_clib\&.edgeIndex_i(self\&._edge))\fC [static]\fP"

.SS "MSD\&.Molecule\&._Edge\&.metaIndex = property(fget = lambda self: self\&._i)\fC [static]\fP"

.SS "MSD\&.Molecule\&._Edge\&.src = property(fget = lambda self: msd_clib\&.src_e(self\&._edge))\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
