.TH "udc::Molecule::NodeIterable" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udc::Molecule::NodeIterable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSD\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeIterator\fP \fBbegin\fP () const"
.br
.ti -1c
.RI "\fBNodeIterator\fP \fBend\fP () const"
.br
.ti -1c
.RI "unsigned int \fBsize\fP () const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMolecule\fP"
.br
.ti -1c
.RI "class \fBNodeIterator\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBMolecule::NodeIterator\fP udc::Molecule::NodeIterable::begin () const"

.SS "\fBMolecule::NodeIterator\fP udc::Molecule::NodeIterable::end () const"

.SS "unsigned int udc::Molecule::NodeIterable::size () const"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBMolecule\fP\fC [friend]\fP"

.SS "friend class \fBNodeIterator\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
