.TH "udc::Molecule::EdgeParameters" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udc::Molecule::EdgeParameters \- Information about an edge between two Nodes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSD\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEdgeParameters\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBJm\fP"
.br
.ti -1c
.RI "double \fBJe1m\fP"
.br
.ti -1c
.RI "double \fBJeem\fP"
.br
.ti -1c
.RI "double \fBbm\fP"
.br
.ti -1c
.RI "\fBVector\fP \fBDm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Information about an edge between two Nodes\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "udc::Molecule::EdgeParameters::EdgeParameters ()"

.SH "Member Data Documentation"
.PP 
.SS "double udc::Molecule::EdgeParameters::bm"

.SS "\fBVector\fP udc::Molecule::EdgeParameters::Dm"

.SS "double udc::Molecule::EdgeParameters::Je1m"

.SS "double udc::Molecule::EdgeParameters::Jeem"

.SS "double udc::Molecule::EdgeParameters::Jm"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
