.TH "udc::Molecule::NodeParameters" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udc::Molecule::NodeParameters \- local parameters  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSD\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNodeParameters\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBSm\fP"
.br
.ti -1c
.RI "double \fBFm\fP"
.br
.ti -1c
.RI "double \fBJe0m\fP"
.br
.ti -1c
.RI "\fBVector\fP \fBAm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
local parameters 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "udc::Molecule::NodeParameters::NodeParameters ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBVector\fP udc::Molecule::NodeParameters::Am"

.SS "double udc::Molecule::NodeParameters::Fm"

.SS "double udc::Molecule::NodeParameters::Je0m"

.SS "double udc::Molecule::NodeParameters::Sm"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
