.TH "udc::UDCException" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udc::UDCException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <udc\&.h>\fP
.PP
Inherits exception\&.
.PP
Inherited by \fBudc::MSD::MoleculeException\fP, and \fBudc::Molecule::DeserializationException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUDCException\fP (const char *message)"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const noexcept"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "udc::UDCException::UDCException (const char * message)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual const char * udc::UDCException::what () const\fC [inline]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
