.TH "udc::MSD::Iterator" 3 "Wed Nov 30 2022" "Version 6.2.1" "MSD" \" -*- nroff -*-
.ad l
.nh
.SH NAME
udc::MSD::Iterator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MSD\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBgetIndex\fP () const"
.br
.ti -1c
.RI "unsigned int \fBgetX\fP () const"
.br
.ti -1c
.RI "unsigned int \fBgetY\fP () const"
.br
.ti -1c
.RI "unsigned int \fBgetZ\fP () const"
.br
.ti -1c
.RI "\fBVector\fP \fBgetSpin\fP () const"
.br
.ti -1c
.RI "\fBVector\fP \fBgetFlux\fP () const"
.br
.ti -1c
.RI "\fBVector\fP \fBgetLocalM\fP () const"
.br
.ti -1c
.RI "\fBVector\fP \fBoperator*\fP () const"
.br
.ti -1c
.RI "\fBVector\fP \fBoperator[]\fP (int) const"
.br
.ti -1c
.RI "\fBoperator unsigned int\fP () const"
.br
.ti -1c
.RI "\fBIterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBIterator\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBIterator\fP \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "\fBIterator\fP & \fBoperator+=\fP (int)"
.br
.ti -1c
.RI "\fBIterator\fP & \fBoperator\-=\fP (int)"
.br
.ti -1c
.RI "\fBIterator\fP \fBoperator+\fP (int) const"
.br
.ti -1c
.RI "\fBIterator\fP \fBoperator\-\fP (int) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBIterator\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBIterator\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBIterator\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBIterator\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBIterator\fP &) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBIterator\fP &) const"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMSD\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBVector\fP udc::MSD::Iterator::getFlux () const"

.SS "unsigned int udc::MSD::Iterator::getIndex () const"

.SS "\fBVector\fP udc::MSD::Iterator::getLocalM () const"

.SS "\fBVector\fP udc::MSD::Iterator::getSpin () const"

.SS "unsigned int udc::MSD::Iterator::getX () const"

.SS "unsigned int udc::MSD::Iterator::getY () const"

.SS "unsigned int udc::MSD::Iterator::getZ () const"

.SS "udc::MSD::Iterator::operator unsigned int () const"

.SS "bool udc::MSD::Iterator::operator!= (const \fBIterator\fP & iter) const"

.SS "\fBVector\fP udc::MSD::Iterator::operator* () const"

.SS "\fBMSD::Iterator\fP udc::MSD::Iterator::operator+ (int n) const"

.SS "\fBMSD::Iterator\fP & udc::MSD::Iterator::operator++ ()"

.SS "\fBMSD::Iterator\fP udc::MSD::Iterator::operator++ (int)"

.SS "\fBMSD::Iterator\fP & udc::MSD::Iterator::operator+= (int n)"

.SS "\fBMSD::Iterator\fP udc::MSD::Iterator::operator\- (int n) const"

.SS "\fBMSD::Iterator\fP & udc::MSD::Iterator::operator\-\- ()"

.SS "\fBMSD::Iterator\fP udc::MSD::Iterator::operator\-\- (int)"

.SS "\fBMSD::Iterator\fP & udc::MSD::Iterator::operator\-= (int n)"

.SS "bool udc::MSD::Iterator::operator< (const \fBIterator\fP & iter) const"

.SS "bool udc::MSD::Iterator::operator<= (const \fBIterator\fP & iter) const"

.SS "bool udc::MSD::Iterator::operator== (const \fBIterator\fP & iter) const"

.SS "bool udc::MSD::Iterator::operator> (const \fBIterator\fP & iter) const"

.SS "bool udc::MSD::Iterator::operator>= (const \fBIterator\fP & iter) const"

.SS "\fBVector\fP udc::MSD::Iterator::operator[] (int n) const"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBMSD\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MSD from the source code\&.
